export function createPost(postData: any, token: string): Promise<any>;
export function getPosts(token?: string | null): Promise<any>;
export function getAllProfiles(): Promise<any>;
export function getProfileById(userId: string): Promise<any>;
export function likePost(postId: string | number, token: string): Promise<any>;
export function commentPost(postId: string | number, content: string, token: string): Promise<any>;
export function getComments(postId: string | number): Promise<any>;
export function sendMessage(receiverId: string, content: string, token: string, file?: File | null): Promise<any>;
export function getMessages(otherUserId: string, token: string): Promise<any>;
export function createConnection(targetUserId: string, token: string): Promise<any>;
export function getMyConnections(token: string): Promise<any>;
export function checkConnection(targetUserId: string, token: string): Promise<any>;
export function createTeamGroup(name: string, members: string[], token: string): Promise<any>;
export function getMyTeamGroups(token: string): Promise<any>;
export function sendTeamMessage(groupId: string, content: string, token: string, file?: File | null): Promise<any>;
export function getTeamMessages(groupId: string, token: string): Promise<any>;
export function deleteTeamGroup(groupId: string, token: string): Promise<any>;
export function addMemberToGroup(groupId: string, userId: string, token: string): Promise<any>;
export function removeMemberFromGroup(groupId: string, userId: string, token: string): Promise<any>;
export function blockUser(targetUserId: string, token: string): Promise<any>;
export function unblockUser(targetUserId: string, token: string): Promise<any>;
export function checkBlocked(targetUserId: string, token: string): Promise<any>;
export function getRecommendations(token: string): Promise<any>;
export function getAllSkills(): Promise<any>;
export function getAllInterests(): Promise<any>;
export function getPost(postId: string | number, token?: string | null): Promise<any>;
export function markMessagesRead(otherUserId: string, token: string): Promise<any>;
export function markGroupRead(groupId: string | number, token: string): Promise<any>;
export function leaveTeamGroup(groupId: string | number, newAdminId: string | null | undefined, token: string): Promise<any>;
export function submitFeedback(feedbackData: any, token?: string | null): Promise<any>;
export function getAdminUsers(token: string): Promise<any>;
export function blockUserAdmin(userId: string | number, token: string): Promise<any>;
export function unblockUserAdmin(userId: string | number, token: string): Promise<any>;
export function getAdminFeedback(token: string): Promise<any>;
export function addAllowedDomain(domain: string, displayName: string, token: string): Promise<any>;
export function getAllowedDomains(token: string): Promise<any>;
export function removeAllowedDomain(id: string | number, token: string): Promise<any>;
export function verifyUserAdmin(userId: string | number, isVerify: boolean, token: string): Promise<any>;
export function deleteUserAdmin(userId: string | number, token: string): Promise<any>;
export function replyToFeedback(feedbackId: string | number, reply: string, token: string): Promise<any>;
export function getMyFeedbackHistory(token: string): Promise<any>;
export function deletePostAdmin(postId: string | number, token: string): Promise<any>;
export function deleteCommentAdmin(commentId: string | number, token: string): Promise<any>;
export function getAdminAnalytics(token: string): Promise<any>;
export function getAnnouncements(token: string): Promise<any>;
export function createAnnouncement(data: { title: string; content: string; is_pinned?: boolean }, token: string): Promise<any>;
export function deleteAnnouncement(id: string | number, token: string): Promise<any>;
