export const INTERESTS = [
    "Hackathons",
    "Competitive Programming",
    "Coding Contests",
    "Kaggle Competitions",
    "Open-Source Contributions",
    "Game Jams",
    "Capture The Flag (CTF)",
    "Innovation Challenges",
    "Robotics Competitions",
    "Startup Pitch Competitions",

    "Machine Learning Projects",
    "Deep Learning Research",
    "Generative AI",
    "AI for Social Good",
    "NLP Applications",
    "Computer Vision Projects",
    "Autonomous Systems",
    "Data Analysis",
    "Data Engineering",
    "Edge AI",

    "Full-Stack Web Development",
    "Frontend Projects",
    "Backend Development",
    "DevOps Practices",
    "API Development",
    "Cloud-Native Applications",
    "Mobile App Development",
    "Cross-Platform App Development",
    "Game Development",
    "Microservices Architecture",

    "FinTech",
    "HealthTech",
    "EdTech",
    "AgriTech",
    "Clean Energy",
    "Smart City Solutions",
    "Cybersecurity",
    "Blockchain Applications",
    "Internet of Things (IoT)",
    "AR/VR Experiences",
    "Autonomous Vehicles",
    "Social Media Platforms",
    "E-commerce Systems",

    "Research Paper Writing",
    "Benchmarking Model Performance",
    "Distributed Systems Research",
    "Algorithms and Optimization",
    "Human-Computer Interaction",
    "Systems Programming",
    "Quantum Computing",
    "High-Performance Computing",

    "Peer Learning",
    "Building Startups",
    "Open-Source Community Work",
    "Mentoring",
    "Project Management",
    "UI/UX Brainstorming",
    "Code Reviews",
    "Agile Collaboration",

    "Creative Coding",
    "Tech and Design",
    "Motion Graphics for Apps",
    "UX Case Studies",
    "Digital Product Prototyping",
    "Minimalist App Design",
    "Gamification Concepts"
];
