export const SKILLS = [
  // Programming Languages
  "C",
  "C++",
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "Go",
  "Rust",
  "C#",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "R",
  "MATLAB",
  "Scala",
  "Dart",
  "Bash / Shell",
  "SQL",
  "NoSQL",

  // Frontend
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Bootstrap",
  "React.js",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "UI/UX Fundamentals",
  "Responsive Design",
  "Web Accessibility (A11y)",
  "DOM Manipulation",

  // Backend
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Laravel",
  "Ruby on Rails",
  "REST API Design",
  "GraphQL",
  "WebSockets",
  "Microservices",
  "Authentication (JWT/OAuth)",

  // Databases
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "MongoDB",
  "Redis",
  "MariaDB",
  "Firebase Firestore",
  "DynamoDB",
  "Elasticsearch",

  // DevOps & Cloud
  "Linux",
  "Docker",
  "Kubernetes",
  "Git",
  "GitHub Actions",
  "Jenkins",
  "CI/CD",
  "Nginx",
  "Terraform",
  "Ansible",
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "Cloud Architecture",
  "Monitoring (Prometheus/Grafana)",

  // AI/ML
  "Machine Learning",
  "Deep Learning",
  "Data Science",
  "NumPy",
  "Pandas",
  "Matplotlib",
  "Scikit-Learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "NLP",
  "Computer Vision",
  "Reinforcement Learning",
  "Model Deployment",
  "ML Ops",

  // Big Data
  "ETL Pipelines",
  "Apache Spark",
  "Apache Kafka",
  "Airflow",
  "Hadoop",
  "Data Modeling",
  "Big Data Systems",

  // Security
  "Network Security",
  "Ethical Hacking",
  "Penetration Testing",
  "OWASP",
  "Cryptography",
  "Identity and Access Management",
  "Vulnerability Assessment",
  "Secure Coding",

  // Mobile
  "Android Development",
  "iOS Development",
  "React Native",
  "Flutter",

  // Game Development
  "Unity",
  "Unreal Engine",
  "Game Physics",
  "Game Design Basics",

  // Systems
  "Computer Networks",
  "Operating Systems",
  "Distributed Systems",
  "Virtualization",
  "System Design",
  "Load Balancing",
  "Caching Strategies",

  // Software Engineering
  "Agile Methodology",
  "Scrum",
  "Unit Testing",
  "Integration Testing",
  "E2E Testing",
  "Jest",
  "Cypress",
  "Design Patterns",
  "Clean Architecture",
  "Refactoring",

  // Tools
  "Postman",
  "Figma",
  "Jira",
  "VS Code",
  "API Testing",
  "Debugging",
]
